# 錯誤碼

[Code0]
one = "未知"
other = "未知"

[Code1]
one = "成功"
other = "成功"

[Code10000]
one = "系统错误"
other = "系统错误"

[Code10001]
one = "未知错误"
other = "未知错误"

[Code10010]
one = "系统繁忙"
other = "系统繁忙"

[Code10020]
one = "请求过多"
other = "请求过多"

[Code10030]
one = "数据库错误"
other = "数据库错误"

[Code10040]
one = "缓存错误"
other = "缓存错误"

[Code10050]
one = "内部 API 错误"
other = "内部 API 错误"

[Code10051]
one = "外部 API 错误"
other = "外部 API 错误"

[Code10052]
one = "内部调用超时"
other = "内部调用超时"

[Code10053]
one = "外部调用超时"
other = "外部调用超时"

[Code10060]
one = "未登录"
other = "未登录"

[Code10061]
one = "用户被封禁"
other = "用户被封禁"

[Code10062]
one = "用户没有设置 PIN 码"
other = "用户没有设置 PIN 码"

[Code10063]
one = "用户已设置 PIN 码"
other = "用户已设置 PIN 码"

[Code10070]
one = "签名无效"
other = "签名无效"

[Code10080]
one = "数据不存在"
other = "数据不存在"

[Code10081]
one = "数据已存在"
other = "数据已存在"

[Code10090]
one = "请求体格式无效"
other = "请求体格式无效"

[Code10100]
one = "请求头格式无效"
other = "请求头格式无效"

[Code10110]
one = "交易失败"
other = "交易失败"

[Code10111]
one = "无此交易类型"
other = "无此交易类型"

[Code10112]
one = "添加资产失败"
other = "添加资产失败"

[Code10113]
one = "扣减资产失败"
other = "扣减资产失败"

[Code10114]
one = "冻结资产失败"
other = "冻结资产失败"

[Code10115]
one = "解冻资产失败"
other = "解冻资产失败"

[Code10116]
one = "增加冻结资产失败"
other = "增加冻结资产失败"

[Code10117]
one = "扣减冻结资产失败"
other = "扣减冻结资产失败"

[Code10130]
one = "无此货币"
other = "无此货币"

[Code10140]
one = "数据格式错误"
other = "数据格式错误"

[Code10150]
one = "参数无效"
other = "参数无效"

[Code10160]
one = "未实现"
other = "未实现"

[Code10170]
one = "无权限"
other = "无权限"

[Code10180]
one = "缓存写入失败"
other = "缓存写入失败"

[Code10181]
one = "缓存读取失败"
other = "缓存读取失败"

[Code10182]
one = "缓存更新失败"
other = "缓存更新失败"

[Code10183]
one = "缓存删除失败"
other = "缓存删除失败"

[Code10184]
one = "缓存过期失败"
other = "缓存过期失败"

[Code10190]
one = "数据库写入失败"
other = "数据库写入失败"

[Code10191]
one = "数据库读取失败"
other = "数据库读取失败"

[Code10192]
one = "数据库更新失败"
other = "数据库更新失败"

[Code10193]
one = "数据库删除失败"
other = "数据库删除失败"

[Code10200]
one = "缺少参数"
other = "缺少参数"

[Code10210]
one = "加密失败"
other = "加密失败"

[Code10211]
one = "解密失败"
other = "解密失败"

[Code10212]
one = "签名失败"
other = "签名失败"

[Code10213]
one = "驗證簽名失敗"
other = "驗證簽名失敗"

[Code10220]
one = "非法操作"
other = "非法操作"

[Code10230]
one = "APP版本过低，请更新至最新版本APP"
other = "APP版本过低，请更新至最新版本APP"

[Code10240]
one = "请稍后重试"
other = "请稍后重试"

[Code10250]
one = "页面大小超过允许的最大限制"
other = "页面大小超过允许的最大限制"

[Code10260]
one = "記憶體不足"
other = "記憶體不足"

[Code10261]
one = "CPU不足"
other = "CPU不足"

[Code100010]
one = "无此用户"
other = "无此用户"

[Code100020]
one = "电邮或PIN码不正确"
other = "电邮或PIN码不正确"

[Code100021]
one = "PIN码不正确"
other = "PIN码不正确"

[Code100030]
one = "资产交易失败"
other = "资产交易失败"

[Code100040]
one = "无效的对象"
other = "无效的对象"

[Code100050]
one = "无此钱包"
other = "无此钱包"

[Code100060]
one = "资产不足"
other = "资产不足"

[Code100070]
one = "预览已过期"
other = "预览已过期"

[Code100080]
one = "转账给自己"
other = "转账给自己"

[Code100090]
one = "token已过期"
other = "token已过期"

[Code100100]
one = "无此汇率"
other = "无此汇率"

[Code100110]
one = "建立websocket channel失败"
other = "建立websocket channel失败"

#### country

    [text_system_country_usa]
    one = "美国"
    other = "美国"

    [text_system_country_jpn]
    one = "日本"
    other = "日本"

    [text_system_country_aut]
    one = "奥地利"
    other = "奥地利"

    [text_system_country_bel]
    one = "比利时"
    other = "比利时"

    [text_system_country_bgr]
    one = "保加利亚"
    other = "保加利亚"

    [text_system_country_cyp]
    one = "赛普勒斯"
    other = "赛普勒斯"

    [text_system_country_cze]
    one = "捷克"
    other = "捷克"

    [text_system_country_deu]
    one = "德国"
    other = "德国"

    [text_system_country_dnk]
    one = "丹麦"
    other = "丹麦"

    [text_system_country_esp]
    one = "西班牙"
    other = "西班牙"

    [text_system_country_est]
    one = "爱沙尼亚"
    other = "爱沙尼亚"

    [text_system_country_fin]
    one = "芬兰"
    other = "芬兰"

    [text_system_country_fra]
    one = "法国"
    other = "法国"

    [text_system_country_grc]
    one = "希腊"
    other = "希腊"

    [text_system_country_hun]
    one = "匈牙利"
    other = "匈牙利"

    [text_system_country_irl]
    one = "爱尔兰"
    other = "爱尔兰"

    [text_system_country_ita]
    one = "义大利"
    other = "义大利"

    [text_system_country_lat]
    one = "拉脱维亚"
    other = "拉脱维亚"

    [text_system_country_lit]
    one = "立陶宛"
    other = "立陶宛"

    [text_system_country_lux]
    one = "卢森堡"
    other = "卢森堡"

    [text_system_country_mlt]
    one = "马尔他"
    other = "马尔他"

    [text_system_country_nld]
    one = "荷兰"
    other = "荷兰"

    [text_system_country_pol]
    one = "波兰"
    other = "波兰"

    [text_system_country_prt]
    one = "葡萄牙"
    other = "葡萄牙"

    [text_system_country_rou]
    one = "罗马尼亚"
    other = "罗马尼亚"

    [text_system_country_svk]
    one = "斯洛伐克"
    other = "斯洛伐克"

    [text_system_country_svn]
    one = "斯洛维尼亚"
    other = "斯洛维尼亚"

    [text_system_country_swe]
    one = "瑞典"
    other = "瑞典"

    [text_system_country_gbr]
    one = "英国"
    other = "英国"

    [text_system_country_chn]
    one = "中国大陸"
    other = "中国大陸"

    [text_system_country_can]
    one = "加拿大"
    other = "加拿大"

    [text_system_country_aus]
    one = "澳洲"
    other = "澳洲"

    [text_system_country_che]
    one = "瑞士"
    other = "瑞士"

    [text_system_country_hkg]
    one = "香港"
    other = "香港"

    [text_system_country_nzl]
    one = "纽西兰"
    other = "纽西兰"

    [text_system_country_mex]
    one = "墨西哥"
    other = "墨西哥"

    [text_system_country_sgp]
    one = "新加坡"
    other = "新加坡"

    [text_system_country_nor]
    one = "挪威"
    other = "挪威"

    [text_system_country_kor]
    one = "南韩"
    other = "南韩"

    [text_system_country_tur]
    one = "土耳其"
    other = "土耳其"

    [text_system_country_ind]
    one = "印度"
    other = "印度"

    [text_system_country_bra]
    one = "巴西"
    other = "巴西"

    [text_system_country_zaf]
    one = "南非"
    other = "南非"

    [text_system_country_rus]
    one = "俄罗斯"
    other = "俄罗斯"

    [text_system_country_twn]
    one = "台湾"
    other = "台湾"

    [text_system_country_isr]
    one = "以色列"
    other = "以色列"

    [text_system_country_are]
    one = "阿拉伯联合大公国"
    other = "阿拉伯联合大公国"

    [text_system_country_arg]
    one = "阿根廷"
    other = "阿根廷"

    [text_system_country_mys]
    one = "马来西亚"
    other = "马来西亚"

    [text_system_country_tha]
    one = "泰国"
    other = "泰国"

    [text_system_country_sau]
    one = "沙乌地阿拉伯"
    other = "沙乌地阿拉伯"

    [text_system_country_idn]
    one = "印尼"
    other = "印尼"

    [text_system_country_pak]
    one = "巴基斯坦"
    other = "巴基斯坦"

    [text_system_country_nga]
    one = "奈及利亚"
    other = "奈及利亚"

    [text_system_country_egy]
    one = "埃及"
    other = "埃及"

    [text_system_country_vnm]
    one = "越南"
    other = "越南"

    [text_system_country_phl]
    one = "菲律宾"
    other = "菲律宾"

    [text_system_country_col]
    one = "哥伦比亚"
    other = "哥伦比亚"

    [text_system_country_chl]
    one = "智利"
    other = "智利"

    [text_system_country_per]
    one = "秘鲁"
    other = "秘鲁"

    [text_system_country_dza]
    one = "阿尔及利亚"
    other = "阿尔及利亚"

    [text_system_country_mar]
    one = "摩洛哥"
    other = "摩洛哥"

    [text_system_country_ken]
    one = "肯亚"
    other = "肯亚"

    [text_system_country_ukr]
    one = "乌克兰"
    other = "乌克兰"

    [text_system_country_afg]
    one = "阿富汗"
    other = "阿富汗"

    [text_system_country_eth]
    one = "衣索比亚"
    other = "衣索比亚"

    [text_system_country_cod]
    one = "刚果民主共和国"
    other = "刚果民主共和国"

    [text_system_country_tza]
    one = "坦尚尼亚"
    other = "坦尚尼亚"

    [text_system_country_uzb]
    one = "乌兹别克"
    other = "乌兹别克"

    [text_system_country_ala]
    one = "奥兰群岛"
    other = "奥兰群岛"

    [text_system_country_alb]
    one = "阿尔巴尼亚"
    other = "阿尔巴尼亚"

    [text_system_country_asm]
    one = "美属萨摩亚"
    other = "美属萨摩亚"

    [text_system_country_and]
    one = "安道尔"
    other = "安道尔"

    [text_system_country_ago]
    one = "安哥拉"
    other = "安哥拉"

    [text_system_country_aia]
    one = "安圭拉"
    other = "安圭拉"

    [text_system_country_ata]
    one = "南极洲"
    other = "南极洲"

    [text_system_country_atg]
    one = "安地卡及巴布达"
    other = "安地卡及巴布达"

    [text_system_country_arm]
    one = "亚美尼亚"
    other = "亚美尼亚"

    [text_system_country_abw]
    one = "阿鲁巴"
    other = "阿鲁巴"

    [text_system_country_aze]
    one = "亚塞拜然"
    other = "亚塞拜然"

    [text_system_country_bhs]
    one = "巴哈马"
    other = "巴哈马"

    [text_system_country_bhr]
    one = "巴林"
    other = "巴林"

    [text_system_country_bgd]
    one = "孟加拉"
    other = "孟加拉"

    [text_system_country_brb]
    one = "巴贝多"
    other = "巴贝多"

    [text_system_country_blr]
    one = "白俄罗斯"
    other = "白俄罗斯"

    [text_system_country_blz]
    one = "贝里斯"
    other = "贝里斯"

    [text_system_country_ben]
    one = "贝南"
    other = "贝南"

    [text_system_country_bmu]
    one = "百慕达"
    other = "百慕达"

    [text_system_country_btn]
    one = "不丹"
    other = "不丹"

    [text_system_country_bol]
    one = "玻利维亚"
    other = "玻利维亚"

    [text_system_country_bes]
    one = "荷兰加勒比区"
    other = "荷兰加勒比区"

    [text_system_country_bih]
    one = "波士尼亚与赫塞哥维纳"
    other = "波士尼亚与赫塞哥维纳"

    [text_system_country_bwa]
    one = "波札那"
    other = "波札那"

    [text_system_country_bvt]
    one = "布威岛"
    other = "布威岛"

    [text_system_country_iot]
    one = "英属印度洋领地"
    other = "英属印度洋领地"

    [text_system_country_brn]
    one = "汶莱"
    other = "汶莱"

    [text_system_country_bfa]
    one = "布吉纳法索"
    other = "布吉纳法索"

    [text_system_country_bdi]
    one = "蒲隆地"
    other = "蒲隆地"

    [text_system_country_cpv]
    one = "维德角"
    other = "维德角"

    [text_system_country_khm]
    one = "柬埔寨"
    other = "柬埔寨"

    [text_system_country_cmr]
    one = "喀麦隆"
    other = "喀麦隆"

    [text_system_country_cym]
    one = "开曼群岛"
    other = "开曼群岛"

    [text_system_country_caf]
    one = "中非共和国"
    other = "中非共和国"

    [text_system_country_tcd]
    one = "查德"
    other = "查德"

    [text_system_country_cxr]
    one = "圣诞岛"
    other = "圣诞岛"

    [text_system_country_cck]
    one = "科科斯群岛"
    other = "科科斯群岛"

    [text_system_country_com]
    one = "葛摩"
    other = "葛摩"

    [text_system_country_cog]
    one = "刚果共和国"
    other = "刚果共和国"

    [text_system_country_cok]
    one = "库克群岛"
    other = "库克群岛"

    [text_system_country_cri]
    one = "哥斯大黎加"
    other = "哥斯大黎加"

    [text_system_country_civ]
    one = "象牙海岸"
    other = "象牙海岸"

    [text_system_country_hrv]
    one = "克罗埃西亚"
    other = "克罗埃西亚"

    [text_system_country_cub]
    one = "古巴"
    other = "古巴"

    [text_system_country_cuw]
    one = "古拉索"
    other = "古拉索"

    [text_system_country_dji]
    one = "吉布地"
    other = "吉布地"

    [text_system_country_dma]
    one = "多米尼克"
    other = "多米尼克"

    [text_system_country_dom]
    one = "多明尼加"
    other = "多明尼加"

    [text_system_country_ecu]
    one = "厄瓜多"
    other = "厄瓜多"

    [text_system_country_slv]
    one = "萨尔瓦多"
    other = "萨尔瓦多"

    [text_system_country_gnq]
    one = "赤道几内亚"
    other = "赤道几内亚"

    [text_system_country_eri]
    one = "厄利垂亚"
    other = "厄利垂亚"

    [text_system_country_swz]
    one = "史瓦帝尼"
    other = "史瓦帝尼"

    [text_system_country_flk]
    one = "福克兰群岛"
    other = "福克兰群岛"

    [text_system_country_fro]
    one = "法罗群岛"
    other = "法罗群岛"

    [text_system_country_fji]
    one = "斐济"
    other = "斐济"

    [text_system_country_guf]
    one = "法属圭亚那"
    other = "法属圭亚那"

    [text_system_country_pyf]
    one = "法属玻里尼西亚"
    other = "法属玻里尼西亚"

    [text_system_country_atf]
    one = "法属南部领地"
    other = "法属南部领地"

    [text_system_country_gab]
    one = "加彭"
    other = "加彭"

    [text_system_country_gmb]
    one = "甘比亚"
    other = "甘比亚"

    [text_system_country_geo]
    one = "乔治亚"
    other = "乔治亚"

    [text_system_country_gha]
    one = "迦纳"
    other = "迦纳"

    [text_system_country_gib]
    one = "直布罗陀"
    other = "直布罗陀"

    [text_system_country_grl]
    one = "格陵兰"
    other = "格陵兰"

    [text_system_country_grd]
    one = "格瑞那达"
    other = "格瑞那达"

    [text_system_country_glp]
    one = "瓜地洛普"
    other = "瓜地洛普"

    [text_system_country_gum]
    one = "关岛"
    other = "关岛"

    [text_system_country_gtm]
    one = "瓜地马拉"
    other = "瓜地马拉"

    [text_system_country_ggy]
    one = "根西岛"
    other = "根西岛"

    [text_system_country_gin]
    one = "几内亚"
    other = "几内亚"

    [text_system_country_gnb]
    one = "几内亚比索"
    other = "几内亚比索"

    [text_system_country_guy]
    one = "盖亚那"
    other = "盖亚那"

    [text_system_country_hti]
    one = "海地"
    other = "海地"

    [text_system_country_hmd]
    one = "赫德岛及麦唐纳群岛"
    other = "赫德岛及麦唐纳群岛"

    [text_system_country_vat]
    one = "梵蒂冈"
    other = "梵蒂冈"

    [text_system_country_hnd]
    one = "宏都拉斯"
    other = "宏都拉斯"

    [text_system_country_isl]
    one = "冰岛"
    other = "冰岛"

    [text_system_country_irn]
    one = "伊朗"
    other = "伊朗"

    [text_system_country_irq]
    one = "伊拉克"
    other = "伊拉克"

    [text_system_country_imn]
    one = "曼岛"
    other = "曼岛"

    [text_system_country_jam]
    one = "牙买加"
    other = "牙买加"

    [text_system_country_jey]
    one = "泽西岛"
    other = "泽西岛"

    [text_system_country_jor]
    one = "约旦"
    other = "约旦"

    [text_system_country_kaz]
    one = "哈萨克"
    other = "哈萨克"

    [text_system_country_kir]
    one = "吉里巴斯"
    other = "吉里巴斯"

    [text_system_country_prk]
    one = "北韩"
    other = "北韩"

    [text_system_country_kwt]
    one = "科威特"
    other = "科威特"

    [text_system_country_kgz]
    one = "吉尔吉斯"
    other = "吉尔吉斯"

    [text_system_country_lao]
    one = "寮国"
    other = "寮国"

    [text_system_country_lva]
    one = "拉脱维亚"
    other = "拉脱维亚"

    [text_system_country_lbn]
    one = "黎巴嫩"
    other = "黎巴嫩"

    [text_system_country_lso]
    one = "赖索托"
    other = "赖索托"

    [text_system_country_lbr]
    one = "赖比瑞亚"
    other = "赖比瑞亚"

    [text_system_country_lby]
    one = "利比亚"
    other = "利比亚"

    [text_system_country_lie]
    one = "列支敦斯登"
    other = "列支敦斯登"

    [text_system_country_ltu]
    one = "立陶宛"
    other = "立陶宛"

    [text_system_country_mac]
    one = "澳门"
    other = "澳门"

    [text_system_country_mdg]
    one = "马达加斯加"
    other = "马达加斯加"

    [text_system_country_mwi]
    one = "马拉威"
    other = "马拉威"

    [text_system_country_mdv]
    one = "马尔地夫"
    other = "马尔地夫"

    [text_system_country_mli]
    one = "马利"
    other = "马利"

    [text_system_country_mhl]
    one = "马绍尔群岛"
    other = "马绍尔群岛"

    [text_system_country_mtq]
    one = "马丁尼克"
    other = "马丁尼克"

    [text_system_country_mrt]
    one = "茅利塔尼亚"
    other = "茅利塔尼亚"

    [text_system_country_mus]
    one = "模里西斯"
    other = "模里西斯"

    [text_system_country_myt]
    one = "马约特"
    other = "马约特"

    [text_system_country_fsm]
    one = "密克罗尼西亚"
    other = "密克罗尼西亚"

    [text_system_country_mda]
    one = "摩尔多瓦"
    other = "摩尔多瓦"

    [text_system_country_mco]
    one = "摩纳哥"
    other = "摩纳哥"

    [text_system_country_mng]
    one = "蒙古"
    other = "蒙古"

    [text_system_country_mne]
    one = "蒙特内哥罗"
    other = "蒙特内哥罗"

    [text_system_country_msr]
    one = "蒙哲腊"
    other = "蒙哲腊"

    [text_system_country_moz]
    one = "莫三比克"
    other = "莫三比克"

    [text_system_country_mmr]
    one = "缅甸"
    other = "缅甸"

    [text_system_country_nam]
    one = "纳米比亚"
    other = "纳米比亚"

    [text_system_country_nru]
    one = "诺鲁"
    other = "诺鲁"

    [text_system_country_npl]
    one = "尼泊尔"
    other = "尼泊尔"

    [text_system_country_ncl]
    one = "新喀里多尼亚"
    other = "新喀里多尼亚"

    [text_system_country_nic]
    one = "尼加拉瓜"
    other = "尼加拉瓜"

    [text_system_country_ner]
    one = "尼日"
    other = "尼日"

    [text_system_country_niu]
    one = "纽埃"
    other = "纽埃"

    [text_system_country_nfk]
    one = "诺福克岛"
    other = "诺福克岛"

    [text_system_country_mkd]
    one = "北马其顿"
    other = "北马其顿"

    [text_system_country_mnp]
    one = "北马利安纳群岛"
    other = "北马利安纳群岛"

    [text_system_country_omn]
    one = "阿曼"
    other = "阿曼"

    [text_system_country_plw]
    one = "帛琉"
    other = "帛琉"

    [text_system_country_pse]
    one = "巴勒斯坦"
    other = "巴勒斯坦"

    [text_system_country_pan]
    one = "巴拿马"
    other = "巴拿马"

    [text_system_country_png]
    one = "巴布亚纽几内亚"
    other = "巴布亚纽几内亚"

    [text_system_country_pry]
    one = "巴拉圭"
    other = "巴拉圭"

    [text_system_country_pcn]
    one = "皮特肯群岛"
    other = "皮特肯群岛"

    [text_system_country_pri]
    one = "波多黎各"
    other = "波多黎各"

    [text_system_country_qat]
    one = "卡达"
    other = "卡达"

    [text_system_country_reu]
    one = "留尼旺"
    other = "留尼旺"

    [text_system_country_rwa]
    one = "卢安达"
    other = "卢安达"

    [text_system_country_blm]
    one = "圣巴瑟米"
    other = "圣巴瑟米"

    [text_system_country_shn]
    one = "圣赫勒拿、阿森松和特里斯坦达库尼亚"
    other = "圣赫勒拿、阿森松和特里斯坦达库尼亚"

    [text_system_country_kna]
    one = "圣克里斯多福及尼维斯"
    other = "圣克里斯多福及尼维斯"

    [text_system_country_lca]
    one = "圣露西亚"
    other = "圣露西亚"

    [text_system_country_maf]
    one = "法属圣马丁"
    other = "法属圣马丁"

    [text_system_country_spm]
    one = "圣皮埃与密克隆群岛"
    other = "圣皮埃与密克隆群岛"

    [text_system_country_vct]
    one = "圣文森及格瑞那丁"
    other = "圣文森及格瑞那丁"

    [text_system_country_wsm]
    one = "萨摩亚"
    other = "萨摩亚"

    [text_system_country_smr]
    one = "圣马利诺"
    other = "圣马利诺"

    [text_system_country_stp]
    one = "圣多美普林西比"
    other = "圣多美普林西比"

    [text_system_country_sen]
    one = "塞内加尔"
    other = "塞内加尔"

    [text_system_country_srb]
    one = "塞尔维亚"
    other = "塞尔维亚"

    [text_system_country_syc]
    one = "塞席尔"
    other = "塞席尔"

    [text_system_country_sle]
    one = "狮子山"
    other = "狮子山"

    [text_system_country_sxm]
    one = "荷属圣马丁"
    other = "荷属圣马丁"

    [text_system_country_slb]
    one = "索罗门群岛"
    other = "索罗门群岛"

    [text_system_country_som]
    one = "索马利亚"
    other = "索马利亚"

    [text_system_country_sgs]
    one = "南乔治亚与南桑威奇群岛"
    other = "南乔治亚与南桑威奇群岛"

    [text_system_country_ssd]
    one = "南苏丹"
    other = "南苏丹"

    [text_system_country_lka]
    one = "斯里兰卡"
    other = "斯里兰卡"

    [text_system_country_sdn]
    one = "苏丹"
    other = "苏丹"

    [text_system_country_sur]
    one = "苏利南"
    other = "苏利南"

    [text_system_country_sjm]
    one = "斯瓦巴和扬马延"
    other = "斯瓦巴和扬马延"

    [text_system_country_syr]
    one = "叙利亚"
    other = "叙利亚"

    [text_system_country_tjk]
    one = "塔吉克"
    other = "塔吉克"

    [text_system_country_tls]
    one = "东帝汶"
    other = "东帝汶"

    [text_system_country_tgo]
    one = "多哥"
    other = "多哥"

    [text_system_country_tkl]
    one = "托克劳"
    other = "托克劳"

    [text_system_country_ton]
    one = "东加"
    other = "东加"

    [text_system_country_tto]
    one = "千里达及托巴哥"
    other = "千里达及托巴哥"

    [text_system_country_tun]
    one = "突尼西亚"
    other = "突尼西亚"

    [text_system_country_tkm]
    one = "土库曼"
    other = "土库曼"

    [text_system_country_tca]
    one = "土克凯可群岛"
    other = "土克凯可群岛"

    [text_system_country_tuv]
    one = "吐瓦鲁"
    other = "吐瓦鲁"

    [text_system_country_uga]
    one = "乌干达"
    other = "乌干达"

    [text_system_country_umi]
    one = "美国本土外小岛屿"
    other = "美国本土外小岛屿"

    [text_system_country_ury]
    one = "乌拉圭"
    other = "乌拉圭"

    [text_system_country_vut]
    one = "万那杜"
    other = "万那杜"

    [text_system_country_ven]
    one = "委内瑞拉"
    other = "委内瑞拉"

    [text_system_country_vgb]
    one = "英属维京群岛"
    other = "英属维京群岛"

    [text_system_country_vir]
    one = "美属维京群岛"
    other = "美属维京群岛"

    [text_system_country_wlf]
    one = "瓦利斯和富图纳"
    other = "瓦利斯和富图纳"

    [text_system_country_esh]
    one = "西撒哈拉"
    other = "西撒哈拉"

    [text_system_country_yem]
    one = "叶门"
    other = "叶门"

    [text_system_country_zmb]
    one = "尚比亚"
    other = "尚比亚"

    [text_system_country_zwe]
    one = "辛巴威"
    other = "辛巴威"
